export const songData = {
    
    // Taylor Swift
    albumOne: [
        "Tim McGraw",
        "Picture to Burn",
        "Teardrops on My Guitar",
        "A Place in This World",
        "Cold as You",
        "The Outside",
        "Tied Together With a Smile",
        "Stay Beautiful",
        "Should've Said No",
        "Mary's Song (Oh My My My)",
        "Our Song",
        "I'm Only Me When I'm With You",
        "Invisible",
        "A Perfectly Good Heart",
        "1st Phone Call With Tim McGraw",
        "Teardrops on My Guitar (pop version)"
    ],

    // Fearless (Taylor's Version)
    albumTwo: [
        "Fearless",
        "Fifteen",
        "Love Story",
        "Hey Stephen",
        "White Horse",
        "You Belong With Me",
        "Breathe (ft. Colbie Caillat)",
        "Tell Me Why",
        "You're Not Sorry",
        "The Way I Loved You",
        "Forever & Always",
        "The Best Day",
        "Change",
        "Jump Then Fall",
        "Untouchable",
        "Forever & Always (Piano Ver.)",
        "Come In With The Rain",
        "Superstar",
        "The Other Side of the Door",
        "Today Was a Fairytale",
        "You All Over Me (ft. Maren Morris)",
        "Mr. Perfectly Fine",
        "We Were Happy",
        "That's When (ft. Keith Urban)",
        "Don't You",
        "Bye Bye Baby",
        "Love Story (Elvira remix)"
    ],

    // Speak Now (Taylor's Version)
    albumThree: [
        "Mine",
        "Sparks Fly",
        "Back to December",
        "Speak Now",
        "Dear John",
        "Mean",
        "The Story of Us",
        "Never Grow Up",
        "Enchanted",
        "Better than Revenge",
        "Innocent",
        "Haunted",
        "Last Kiss",
        "Long Live",
        "Ours",
        "Superman",
        "Electric Touch (ft. Fall Out Boy)",
        "When Emma Falls in Love",
        "I Can See You",
        "Castles Crumbling (ft. Hayley Williams)",
        "Foolish One",
        "Timeless"
    ],

    // Red (Taylor's Version)
    albumFour: [
        "State of Grace",
        "Red",
        "Treacherous",
        "I Knew You Were Trouble",
        "All Too Well",
        "22",
        "I Almost Do",
        "We Are Never Ever Getting Back Together",
        "Stay Stay Stay",
        "The Last Time (ft. Gary Lightbody)",
        "Holy Ground",
        "Sad Beautiful Tragic",
        "The Lucky One",
        "Everything Has Changed (ft. Ed Sheeran)",
        "Starlight",
        "Begin Again",
        "The Moment I Knew",
        "Come Back... Be Here",
        "Girl at Home",
        "State of Grace (acoustic version)",
        "Ronan",
        "Better Man",
        "Nothing New (ft. Phoebe Bridgers)",
        "Babe",
        "Message in a Bottle",
        "I Bet You Think About Me (ft. Chris Stapleton)",
        "Forever Winter",
        "Run (ft. Ed Sheeran)",
        "The Very First Night",
        "All Too Well (10 Minute Version)"
    ]
};