export const songData = {
    
    // Taylor Swift
    albumOne: [
        "Tim McGraw",
        "Picture to Burn",
        "Teardrops on My Guitar",
        "A Place in This World",
        "Cold as You",
        "The Outside",
        "Tied Together With a Smile",
        "Stay Beautiful",
        "Should've Said No",
        "Mary's Song (Oh My My My)",
        "Our Song",
        "I'm Only Me When I'm With You",
        "Invisible",
        "A Perfectly Good Heart",
        "1st Phone Call With Tim McGraw",
        "Teardrops on My Guitar (pop version)"
    ],

    // Fearless (Taylor's Version)
    albumTwo: [
        "Fearless",
        "Fifteen",
        "Love Story",
        "Hey Stephen",
        "White Horse",
        "You Belong With Me",
        "Breathe (ft. Colbie Caillat)",
        "Tell Me Why",
        "You're Not Sorry",
        "The Way I Loved You",
        "Forever & Always",
        "The Best Day",
        "Change",
        "Jump Then Fall",
        "Untouchable",
        "Forever & Always (Piano Ver.)",
        "Come In With The Rain",
        "Superstar",
        "The Other Side of the Door",
        "Today Was a Fairytale",
        "You All Over Me (ft. Maren Morris)",
        "Mr. Perfectly Fine",
        "We Were Happy",
        "That's When (ft. Keith Urban)",
        "Don't You",
        "Bye Bye Baby",
        "Love Story (Elvira remix)"
    ],

    // Speak Now (Taylor's Version)
    albumThree: [
        "Mine",
        "Sparks Fly",
        "Back to December",
        "Speak Now",
        "Dear John",
        "Mean",
        "The Story of Us",
        "Never Grow Up",
        "Enchanted",
        "Better than Revenge",
        "Innocent",
        "Haunted",
        "Last Kiss",
        "Long Live",
        "Ours",
        "Superman",
        "Electric Touch (ft. Fall Out Boy)",
        "When Emma Falls in Love",
        "I Can See You",
        "Castles Crumbling (ft. Hayley Williams)",
        "Foolish One",
        "Timeless"
    ],

    // Red (Taylor's Version)
    albumFour: [
        "State of Grace",
        "Red",
        "Treacherous",
        "I Knew You Were Trouble",
        "All Too Well",
        "22",
        "I Almost Do",
        "We Are Never Ever Getting Back Together",
        "Stay Stay Stay",
        "The Last Time (ft. Gary Lightbody)",
        "Holy Ground",
        "Sad Beautiful Tragic",
        "The Lucky One",
        "Everything Has Changed (ft. Ed Sheeran)",
        "Starlight",
        "Begin Again",
        "The Moment I Knew",
        "Come Back... Be Here",
        "Girl at Home",
        "State of Grace (acoustic version)",
        "Ronan",
        "Better Man",
        "Nothing New (ft. Phoebe Bridgers)",
        "Babe",
        "Message in a Bottle",
        "I Bet You Think About Me (ft. Chris Stapleton)",
        "Forever Winter",
        "Run (ft. Ed Sheeran)",
        "The Very First Night",
        "All Too Well (10 Minute Version)"
    ],

    // 1989 (Taylor's Version)
    albumFive: [
        "Welcome to New York",
        "Blank Space",
        "Style",
        "Out of the Woods",
        "All You Had to Do Was Stay",
        "Shake It Off",
        "I Wish You Would",
        "Bad Blood",
        "Wildest Dreams",
        "How You Get the Girl",
        "This Love",
        "I Know Places",
        "Clean",
        "Wonderland",
        "You Are in Love",
        "New Romantics",
        "Slut!",
        "Say Don't Go",
        "Now That We Don't Talk",
        "Suburban Legends",
        "Is It Over Now?",
        "Sweeter than Fiction",
        "Bad Blood (ft. Kendrick Lamar)"
    ],

    // reputation
    albumSix: [
        "...Ready for It?",
        "End Game (ft. Ed Sheeran and Future)",
        "I Did Something Bad",
        "Don't Blame Me",
        "Delicate",
        "Look What You Made Me Do",
        "So It Goes...",
        "Gorgeous",
        "Getaway Car",
        "King of My Heart",
        "Dancing with Our Hands Tied",
        "Dress",
        "This Is Why We Can't Have Nice Things",
        "Call It What You Want",
        "New Year's Day"
    ],

    // Lover
    albumSeven: [
        "I Forgot That You Existed",
        "Cruel Summer",
        "Lover",
        "The Man",
        "The Archer",
        "I Think He Knows",
        "Miss Americana & The Heartbreak Prince",
        "Paper Rings",
        "Cornelia Street",
        "Death by a Thousand Cuts",
        "London Boy",
        "Soon You'll Get Better (ft. The Chicks)",
        "False God",
        "You Need to Calm Down",
        "Afterglow",
        "Me! (ft. Brendon Urie)",
        "It's Nice to Have a Friend",
        "Daylight",
        "I Forgot That You Existed (Piano/Vocal)",
        "Lover (Piano/Vocal)"
    ],

    // folklore
    albumEight: [
        "the 1",
        "cardigan",
        "the last great american dynasty",
        "exile (ft. Bon Iver)",
        "my tears ricochet",
        "mirrorball",
        "seven",
        "august",
        "this is me trying",
        "illicit affairs",
        "invisible string",
        "mad woman",
        "epiphany",
        "betty",
        "peace",
        "hoax",
        "the lakes"
    ],

    // evermore
    albumNine: [
        "willow",
        "champagne problems",
        "gold rush",
        "'tis the damn season",
        "tolerate it",
        "no body, no crime (ft. HAIM)",
        "happiness",
        "dorothea",
        "coney island (ft. The National)",
        "ivy",
        "cowboy like me",
        "long story short",
        "marjorie",
        "closure",
        "evermore (ft. Bon Iver)",
        "right where you left me",
        "it's time to go"
    ],

    // Midnights
    albumTen: [
       "Lavender Haze",
       "Maroon",
       "Anti-Hero",
       "Snow on the Beach (ft. Lana Del Rey)",
       "You're On Your Own, Kid",
       "Midnight Rain",
       "Question...?",
       "Vigilante Shit",
       "Bejeweled",
       "Labyrinth",
       "Karma",
       "Sweet Nothing",
       "Mastermind",
       "Hits Different",
       "You're on Your Own, Kid (Strings remix)",
       "Sweet Nothing (Piano remix)",
       "The Great War",
       "Bigger Than the Whole Sky",
       "Paris",
       "High Infidelity",
       "Glitch",
       "Would've, Could've, Should've",
       "Dear Reader",
       "Snow on the Beach (ft. more Lana Del Rey)",
       "Karma (ft. Ice Spice)",
       "You're Losing Me (From The Vault)"
    ],

    // The Tortured Poets Department
    albumEleven: [
        "Fortnight (ft. Post Malone)",
        "The Tortured Poets Department",
        "My Boy Only Breaks His Favorite Toys",
        "Down Bad",
        "So Long, London",
        "But Daddy I Love Him",
        "Fresh Out the Slammer",
        "Florida!!! (ft. Florence and the Machine)",
        "Guilty as Sin?",
        "Who's Afraid of Little Old Me?",
        "I Can Fix Him (No Really I Can)",
        "loml",
        "I Can Do It with a Broken Heart",
        "The Smallest Man Who Ever Lived",
        "The Alchemy",
        "Clara Bow",
        "The Black Dog",
        "imgonnagetyouback",
        "The Albatross",
        "Chloe or Sam or Sophia or Marcus",
        "How Did It End?",
        "So High School",
        "I Hate It Here",
        "thanK you aIMee",
        "I Look in People's Windows",
        "The Prophecy",
        "Cassandra",
        "Peter",
        "The Bolter",
        "Robin",
        "The Manuscript",
        "Fortnight (ft. Post Malone; acoustic ver.)",
        "Down Bad (acousitc ver.)",
        "But Daddy I Love Him (acoustic ver.)",
        "Guilty as Sin? (acoustic ver.)"
    ]
};